@startuml name use-case diagram

actor User
actor Deanery

User --> (Перегляд розкладу)
User --> (Перегляд задач)
Deanery --> (Перегляд розкладу)
Deanery --> (Перегляд задач)

(Перегляд розкладу)-->(Внесення даних з форми)

 (Перегляд задач)-->(Внесення файлових даних)
  (Перегляд задач)-->(Внесення даних з клавіатури)
  
  (Внесення файлових даних) --> (Обробка файлу)
  (Внесення даних з клавіатури) --> (Обробка даних)
  
  (Обробка файлу) --> (Введення даних)
  (Обробка даних) --> (Введення даних)

(Введення даних) --> (Обчислення вартості)
(Обчислення вартості) .down.> (Перевірка коректності даних) : <<include>>

(Обчислення вартості) --> (Розрахунок витрат)
(Перевірка коректності даних) .down.> (Перевірка на помилки) : <<extend>>

@enduml